# Generated by Django 3.2.2 on 2022-12-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0004_auto_20221219_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainningresults',
            name='is_last',
            field=models.BooleanField(blank=True, db_column='is_last', default=False, null=True),
        ),
    ]
