# Generated by Django 3.2.2 on 2022-12-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0005_trainningresults_is_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramsconfigs',
            name='configaftertrainmodelpath',
            field=models.CharField(blank=True, db_column='expAfterTrainModelPath', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paramsconfigs',
            name='configfilelog',
            field=models.CharField(blank=True, db_column='expFileLog', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('predictid', models.AutoField(db_column='predictId', primary_key=True, serialize=False)),
                ('inputpath', models.CharField(blank=True, db_column='inputPath', max_length=800, null=True)),
                ('inputpath2', models.CharField(blank=True, db_column='inputPath2', max_length=800, null=True)),
                ('outputpath', models.CharField(blank=True, db_column='outputPath', max_length=800, null=True)),
                ('accuracy', models.FloatField(db_column='accuracy')),
                ('details', models.CharField(blank=True, db_column='details', max_length=800, null=True)),
                ('configid', models.ForeignKey(blank=True, db_column='resultConfigID', null=True, on_delete=django.db.models.deletion.CASCADE, to='expAI.paramsconfigs')),
            ],
            options={
                'db_table': 'predict',
                'managed': True,
            },
        ),
    ]
