# Generated by Django 3.2.2 on 2022-12-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0006_auto_20221222_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='datatype',
            field=models.CharField(blank=True, db_column='datatype', max_length=200, null=True),
        ),
    ]
