# Generated by Django 3.2.2 on 2022-12-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0007_predict_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='accuracy',
            field=models.FloatField(blank=True, db_column='accuracy', null=True),
        ),
    ]
