# Generated by Django 3.2 on 2023-01-09 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0009_experiments_expstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usrclass',
        ),
        migrations.CreateModel(
            name='ClassUser',
            fields=[
                ('class_user_id', models.AutoField(db_column='classUserID', primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, db_column='status', null=True)),
                ('time_regis', models.DateTimeField(default=django.utils.timezone.now, verbose_name='register time')),
                ('time_approve', models.DateTimeField(default=django.utils.timezone.now, verbose_name='approve time')),
                ('class_id', models.ForeignKey(blank=True, db_column='classid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expAI.class')),
                ('user_id', models.ForeignKey(blank=True, db_column='ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
