# Generated by Django 3.2 on 2023-01-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0010_auto_20230109_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classuser',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='classuser',
            table='ClassUser',
        ),
    ]
