# Generated by Django 3.2 on 2023-01-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expAI', '0011_auto_20230109_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chose_class',
            field=models.BooleanField(default=False, verbose_name='User chose class'),
        ),
    ]
